### PR TITLE
Fix openfast with oneapi

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Review by psakievich — APPROVED** [review]

**Comment by jrood-nrel** [comment]
I'm not confident that patch works for 3.5.3.

**Comment by psakievich** [comment]
ah sorry. looks like I rushed the gun. We can merge a follow on if it fails.

**Comment by jrood-nrel** [comment]
No problem, I will make a PR for it.

**Comment by marchdf** [comment]
It worked for me... but maybe I got lucky?

**Pull request merged**
