### PR TITLE
Update kestrel configs

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by marchdf** [comment]
Intel builds work just fine (debug and non-debug)

GCC builds hit a trilinos error:
```
      4867    In file included from /kfs2/projects/hfm/mhenryde/exawind/exawind-manager/stage/spack-stage-trilinos-develop-biuqkovesnltm5u24ebifyvl6jcz7jm4/spack-src/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.h:25,
     4868                     from /kfs2/projects/hfm/mhenryde/exawind/exawind-manager/stage/spack-stage-trilinos-develop-biuqkovesnltm5u24ebifyvl6jcz7jm4/spack-src/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C:8:
     4869    /kfs2/projects/hfm/mhenryde/exawind/exawind-manager/stage/spack-stage-trilinos-develop-biuqkovesnltm5u24ebifyvl6jcz7jm4/spack-src/packages/seacas/libraries/ioss/src/Ioss_Decomposition.h: In member function 'void Ioss::Decomposition<INT>::communicat
             e_element_data(T*, T*, size_t) const':
  >> 4870    /kfs2/projects/hfm/mhenryde/exawind/exawind-manager/stage/spack-stage-trilinos-develop-biuqkovesnltm5u24ebifyvl6jcz7jm4/spack-src/packages/seacas/libraries/ioss/src/Ioss_Decomposition.h:360:15: error: 'MY_Alltoallv' is not a member of 'Ioss'
     4871      360 |         Ioss::MY_Alltoallv(export_data, exportElementCount, exportElementIndex, import_data,
     4872          |               ^~~~~~~~~~~~
```
This is with 15.1.1 and with `develop`. 

[Full error: spack-build-out.txt](https://github.com/Exawind/exawind-manager/files/15080925/spack-build-out.txt)


DAG:
```
==> Concretized exawind@master%gcc build_type=Release ^amr-wind@main%gcc build_type=Release ^nalu-wind@master%gcc build_type=Release ^tioga@develop%gcc build_type=Release ^trilinos@develop
 -   jbruv3e  exawind@master%gcc@12.2.0~amr_wind_gpu~asan~cdash_submit~cuda~fsi~gpu-aware-mpi~hypre~ipo~nalu_wind_gpu~ninja~openfast~rocm~stk_simd~sycl~tiny_profile~umpire build_system=cmake build_type=Release ctest_args='-R unit' dev_path=/kfs2/projects/hfm/mhenryde/exawind/exawind-manager/environments/exawind-dev-gcc/exawind generator=make reference_golds=default arch=linux-rhel8-sapphirerapids
[+]  rpqfuxz      ^amr-wind@main%gcc@12.2.0~asan~ascent~cdash_submit~clangtidy~cppcheck~cuda~gpu-aware-mpi~hdf5~hypre~ipo~masa+mpi+netcdf~ninja~openfast~openmp~rocm+shared~sycl+tests+tiny_profile~umpire build_system=cmake build_type=Release ctest_args='-R unit' dev_path=/kfs2/projects/hfm/mhenryde/exawind/exawind-manager/environments/exawind-dev-gcc/amr-wind generator=make reference_golds=default arch=linux-rhel8-sapphirerapids
[+]  6mod4bi          ^netcdf-c@4.9.2%gcc@12.2.0~blosc~byterange~dap~fsync~hdf4~jna~mpi~nczarr_zip+optimize+parallel-netcdf+pic+shared~szip~zstd build_system=autotools patches=0161eb8 arch=linux-rhel8-sapphirerapids
[+]  75aimps              ^bzip2@1.0.8%gcc@12.2.0~debug~pic+shared build_system=generic arch=linux-rhel8-sapphirerapids
[+]  sihpm4m                  ^diffutils@3.10%gcc@12.2.0 build_system=autotools arch=linux-rhel8-sapphirerapids
[+]  vo3cle6                      ^libiconv@1.17%gcc@12.2.0 build_system=autotools libs=shared,static arch=linux-rhel8-sapphirerapids
[+]  hgeeiib              ^parallel-netcdf@1.12.3%gcc@12.2.0~burstbuffer+cxx~fortran+pic+shared build_system=autotools arch=linux-rhel8-sapphirerapids
[+]  z2jpwah                  ^m4@1.4.19%gcc@12.2.0~sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel8-sapphirerapids
[+]  ok4kait      ^cmake@3.27.9%gcc@12.2.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel8-sapphirerapids
[+]  6ryk63g          ^curl@8.6.0%gcc@12.2.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel8-sapphirerapids
[+]  lpli64o              ^openssl@3.2.1%gcc@12.2.0~docs+shared build_system=generic certs=system arch=linux-rhel8-sapphirerapids
[+]  pauoafs              ^pkgconf@1.9.5%gcc@12.2.0 build_system=autotools arch=linux-rhel8-sapphirerapids
[+]  bmb5l4z          ^ncurses@6.4%gcc@12.2.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-rhel8-sapphirerapids
[+]  vppulnh          ^zlib-ng@2.1.6%gcc@12.2.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-rhel8-sapphirerapids
[e]  seppkuq      ^cray-mpich@8.1.28%gcc@12.2.0+wrappers build_system=generic arch=linux-rhel8-sapphirerapids
[+]  doo5r3d      ^gcc-runtime@12.2.0%gcc@12.2.0 build_system=generic arch=linux-rhel8-sapphirerapids
[+]  yfctfgm      ^gmake@4.4.1%gcc@12.2.0~guile build_system=generic arch=linux-rhel8-sapphirerapids
 -   i3svqhn      ^nalu-wind@master%gcc@12.2.0~asan~boost~catalyst~cdash_submit~cuda~fftw~fsi~gpu-aware-mpi~hypre~ipo~ninja~openfast+pic~rocm+shared~stk_simd+tests+tioga+trilinos-solvers~umpire+unit-tests~wind-utils abs_tol=1e-15 build_system=cmake build_type=Release ctest_args='-R unit' cxxstd=17 dev_path=/kfs2/projects/hfm/mhenryde/exawind/exawind-manager/environments/exawind-dev-gcc/nalu-wind generator=make reference_golds=default rel_tol=1e-12 arch=linux-rhel8-sapphirerapids
[+]  jhcderr          ^nccmp@1.9.1.0%gcc@12.2.0~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel8-sapphirerapids
[+]  rzwhzre      ^tioga@develop%gcc@12.2.0~asan~cdash_submit~ipo~ninja~nodegid+pic+shared~stats~timers build_system=cmake build_type=Release ctest_args='-R unit' dev_path=/kfs2/projects/hfm/mhenryde/exawind/exawind-manager/environments/exawind-dev-gcc/tioga generator=make reference_golds=default arch=linux-rhel8-sapphirerapids
 -   biuqkov      ^trilinos@develop%gcc@12.2.0~adelus~adios2~amesos+amesos2~anasazi~asan~aztec~basker+belos~boost~cdash_submit~chaco~complex~cuda~cuda_rdc~debug~dtk~epetra~epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings+exodus+explicit_template_instantiation~float~fortran+gtest+hdf5~hypre~ifpack+ifpack2~intrepid~intrepid2~ipo~isorropia+kokkos~mesquite~minitensor~ml~mpi+muelu~mumps~ninja~nox~openmp~pamgen~panzer~phalanx+pic~piro~python~rocm~rocm_rdc~rol~rythmos~sacado~scorec+shards+shared~shylu+stk~stk_simd~stk_unit_tests~stokhos~stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus~test~thyra+tpetra~trilinoscouplings~wrapper~x11+zoltan~zoltan2 build_system=cmake build_type=Release ctest_args='-R unit' cxxstd=17 generator=make gotype=long reference_golds=default arch=linux-rhel8-sapphirerapids
[+]  t42diu4          ^cgns@4.4.0%gcc@12.2.0~base_scope~fortran~hdf5~int64~ipo~legacy~mem_debug+mpi~pic+scoping+shared~static~testing~tools build_system=cmake build_type=Release generator=make arch=linux-rhel8-sapphirerapids
[+]  msxmezr          ^hdf5@1.14.3%gcc@12.2.0+cxx~fortran+hl~ipo~java~map~mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8 arch=linux-rhel8-sapphirerapids
[+]  dsp3ooc          ^hwloc@2.9.1%gcc@12.2.0~cairo~cuda~gl~libudev~libxml2~netloc~nvml~oneapi-level-zero~opencl~pci~rocm build_system=autotools libs=shared,static arch=linux-rhel8-sapphirerapids
[+]  5pdeuri          ^kokkos@4.2.01%gcc@12.2.0~aggressive_vectorization~compiler_warnings~cuda~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~hpx~hpx_async_dispatch~hwloc~ipo~memkind~numactl~openmp~openmptarget~pic~rocm+serial+shared~sycl~tests~threads~tuning~wrapper build_system=cmake build_type=Release cxxstd=17 generator=make intel_gpu_arch=none arch=linux-rhel8-sapphirerapids
[+]  c2wzx7k          ^matio@1.5.26%gcc@12.2.0+hdf5+shared+zlib build_system=autotools arch=linux-rhel8-sapphirerapids
[+]  6obszqi          ^metis@5.1.0%gcc@12.2.0~gdb~int64~ipo~real64+shared build_system=cmake build_type=Release generator=make patches=4991da9,93a7903,b1225da arch=linux-rhel8-sapphirerapids
[+]  ivsrtbc          ^openblas@0.3.26%gcc@12.2.0~bignuma~consistent_fpcsr+dynamic_dispatch+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none arch=linux-rhel8-sapphirerapids
[+]  piwmt62              ^perl@5.38.0%gcc@12.2.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel8-sapphirerapids
[+]  6galvoe                  ^berkeley-db@18.1.40%gcc@12.2.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel8-sapphirerapids
[+]  zh4owsi                  ^gdbm@1.23%gcc@12.2.0 build_system=autotools arch=linux-rhel8-sapphirerapids
[+]  pwra3ln                      ^readline@8.2%gcc@12.2.0 build_system=autotools patches=bbf97f1 arch=linux-rhel8-sapphirerapids
[+]  45pki6n      ^yaml-cpp@0.7.0%gcc@12.2.0~ipo+pic+shared~tests build_system=cmake build_type=Release generator=make arch=linux-rhel8-sapphirerapids
```

Thoughts @psakievich ?

**Comment by psakievich** [comment]
Not sure. I see it in the `develop` branch: https://github.com/trilinos/Trilinos/blob/c1660dbbf5270263a73e8117cf3d8dda74d2acf1/packages/seacas/libraries/ioss/src/Ioss_ParallelUtils.h#L273

**Comment by psakievich** [comment]
I'm not super inclined to spend a lot of time on this if we have working debug builds with intel though. I can check on another systems and see if I get the same error the next time I do the gcc config.

**Review by psakievich — APPROVED** [review]

**Review by jrood-nrel — APPROVED** [review]

**Comment by jrood-nrel** [comment]
Very surprised to see Trilinos fail to build with GCC 12. Usually it's Intel that has the build error.

**Pull request merged**
