### PR TITLE
Remove rosco to be maintained in spack

### PR DESCRIPTION
**Pull request by marchdf**
@ndevelder , @psakievich, @lawrenceccheung, @dzalkind, @rybchuk, jfrederik-nrel.

It sounds like we are trying to remove packages maintained in exawind and move those to spack. So I did that in this PR and this one for spack: https://github.com/spack/spack/pull/43822.

~~One thing I couldn't figure out and would like to open for discussion. Right now I removed all versions and just kept 2.9.1. In version 2.9 there was a reorg of the files which means that `root_cmakelists_dir` changed. We could support other versions by doing a conditional on that. I have no problems doing that. The only issue is that I can't get v2.8 and below to build with intel oneapi on Kestrel. So we would have to be ok with that or carry a patch. Since I don't use rosco much, let me know what you think.~~ -> see discussion below, this has been resolved.

### CODE REVIEW

**Comment by rybchuk** [comment]
I think RAAW will be impacted if we can't support v2.8. But, I think we should be able to compile the old way with gcc, and we can probably take the performance hit.

**Comment by marchdf** [comment]
For RAAW, since we currently don't carry a tag for it, do you typically do a develop spec and then checkout that tag?

**Comment by marchdf** [comment]
I am gathering that we want to be able to use older versions of ROSCO, so I will add those back in and we can figure out how to handle the versions that don't work with certain compilers.

**Comment by marchdf** [comment]
FYI I think there's a tagging problem on ROSCO: https://github.com/NREL/ROSCO/issues/337

**Comment by rybchuk** [comment]
Yeah sorry for the annoyance. In my experience, a lot of projects get locked into specific pairings of OpenFAST+ROSCO, and it can be a substantial challenge to switch versions (e.g., in intercomparison projects when running expensive LES)

**Comment by rybchuk** [comment]
> For RAAW, since we currently don't carry a tag for it, do you typically do a develop spec and then checkout that tag?

I haven't personally compiled AMR-Wind + OpenFAST + the RAAW ROSCO version. On the project, our team has a pairing that works on Eagle at the moment, and we're running with that until we can't anymore.

**Comment by marchdf** [comment]
Ok I added back in the previous versions of ROSCO. I can build on version 2.9 on kestrel with intel oneapi. I can't build v2.8. I think one of the issues is that `CMAKE_Fortran_COMPILER_ID = IntelLLVM`. And so it fails this intel check: https://github.com/NREL/ROSCO/blob/main/rosco/controller/CMakeLists.txt#L14 and uses GCC flags. I am not sure why 2.9 still manages to compile but not 2.8. In any event, if I make the test on `IntelLLVM` then I can build version 2.8.

**Comment by marchdf** [comment]
I have an open PR for fixing in ROSCO (https://github.com/NREL/ROSCO/pull/338) and I am going to be adding patches so we can build prior versions.

**Comment by psakievich** [comment]
yeah patches are a great idea. I reviewed your spack PR and mentioned how to ensure known compiler failures for specific versions can be enforced in the package.py.  Ideally a series of small patches could fix it all.  Thanks for doing this @marchdf

**Comment by marchdf** [comment]
@psakievich thanks. I've added the patches. It all seems to work on kestrel now.

**Comment by marchdf** [comment]
Converting to draft. I will update the spack submodule with this once the official spack package goes in.

**Comment by marchdf** [comment]
@psakievich this is ready to go now that rosco is in spack.

**Review by psakievich — APPROVED** [review]

**Pull request merged**
